include: package:lints/recommended.yaml

analyzer:
  errors:
    avoid_print: warning
    annotate_overrides: warning
    always_use_package_imports: warning
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    always_use_package_imports: true
